export class CabValeVerde {

    public id!: number;
	public vdesde!: string;
	public vhasta!: string;
	public cantidad!: number;
	public monto!: number;
	public observacion!: string;
	public tipodoc!: string;
	public freg!: Date;
	public isprint!: boolean;
	public usuario!: string;
	public aprobado!: boolean;
	public pagado!: boolean;
	public usuarioAp!: string;
	public usuarioPr!: string;
	public usuarioPa!: string;
	public fechaPa!: Date;
	public anulado!: boolean;
	public nrofactura!: string;
	public prefijo!: string;
	public rangoini!: number;
	public rangofin!: number;
	public area_id!: number;
	public empleado_id!: number;
	public estadoFinal!: string;
	public idEmpresa!: number;
	public ruc!: string;
	public razonSocial!: string;
	public nombreContacto!: string;
	public telefonoContacto!: string;
	public cargoContacto!: string;
	public emailContacto!: string;
	public areaNombre!: string;
    public empleadoNombre!: string;
    public tipoDocumento!: string;
	public serie!: string;
	public correlativo!: string;
	public fechaEmision!: Date;
	public moneda!: string;
	public montoTotal!: number;
	public usuarioCreacion!: number;
	public usuarioModificacion!: number;
	public fechaCreacion!: Date;
	public fechaModificacion!:Date;
	public tienda!: string;
	public base!: string;
	public datosCliente!: string;
	public clasificacion!: number;
	public subTipDoc!: number;
	public estado!: string;
	public idFormato!: number;
	public rutaImagen!: string | undefined;
	public nrofacturaAnterior!: string;
	public fechaEmisionAnterior!: Date;
	public montoTotalAnterior!: number;

}
