export const environment = {
  production: true,
  //PRODUCCION
  urlSecurity: 'http://VSRVPRDAPP07.ngr.com.pe:9999',
  urlCupones: 'http://VSRVPRDAPP07.ngr.com.pe:9837',
  urlInterfazProducto: 'http://VSRVPRDAPP07.ngr.com.pe:9838',
  urlCuadratura: 'http://VSRVPRDAPP07.ngr.com.pe:9839',
  urlEjecutor: 'http://VSRVPRDAPP07.ngr.com.pe:9845',
  urlEjecutorSybase: 'http://VSRVPRDAPP07.ngr.com.pe:9753',
  urlInterfaz: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazBB: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazDB: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazPP: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazCW: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazPJ: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlInterfazDD: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlReporte: 'http://VSRVPRDAPP07.ngr.com.pe:9811',
  urlCierre: 'http://VSRVPRDAPP07.ngr.com.pe:9899',
  urlRrhh: 'http://VSRVPRDAPP07.ngr.com.pe:9822',
  urlOmnicanal: 'http://VSRVPRDAPP07.ngr.com.pe:9833',
  urlSecurityShared: 'http://vsrvprdweb01.ngr.com.pe/security-shared',
  urlGenesys: 'https://genesys.dev.audex.api-ngr.com/genesys',
  urlOmnicanalA: 'https://api.omnicanal.api-ngr.com/motorpromocion',
  urlTstdrpApi: 'https://prod.api-ngr.com/oauth2/token',
  urlCarta: 'http://VSRVPRDAPP07.ngr.com.pe:9833/api/omnicanal',
  gtype: 'client_credentials',
  clientid: '7tj4d2jf2kenqkra76ga751omni',
  clientsecret: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiomni',
  clientsecretdescuento: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliigen',
  clientidunico: '7tj4d2jf2kenqkra76ga751clienteunico',
  clientsecretunico:
    'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiclienteunico',
  urlAmauta: 'https://api.dev.amauta.api-ngr.com',
};
