export const environment = {
  production: true,
  //PRODUCCION
  urlSecurity: 'http://VSRVPRDAPP07.ngr.com.pe:9999',
  urlCupones: 'http://VSRVPRDAPP07.ngr.com.pe:9837',
  urlInterfazProducto: 'http://VSRVPRDAPP07.ngr.com.pe:9838',
  urlCuadratura: 'http://VSRVPRDAPP07.ngr.com.pe:9839',
  urlEjecutor: 'http://VSRVPRDAPP07.ngr.com.pe:9845',
  urlEjecutorSybase: 'http://VSRVPRDAPP07.ngr.com.pe:9753',
  urlInterfaz: 'http://VSRVPRDAPP07.ngr.com.pe:9842',
  urlReporte: 'http://VSRVPRDAPP07.ngr.com.pe:9811',
  urlCierre: 'http://VSRVPRDAPP07.ngr.com.pe:9899',
  urlRrhh: 'http://VSRVPRDAPP07.ngr.com.pe:9822',
  urlOmnicanal: 'http://VSRVPRDAPP07.ngr.com.pe:9833',
  urlSecurityShared: 'http://vsrvprdweb01.ngr.com.pe/security-shared',
  urlGenesys: 'https://genesys.dev.audex.api-ngr.com/genesys',
  urlOmnicanalA: 'https://api.omnicanal.api-ngr.com/motorpromocion',
  urlTstdrpApi: 'https://prod.api-ngr.com/oauth2/token',
  urlCarta: 'http://VSRVPRDAPP07.ngr.com.pe:9833/api/omnicanal',
  gtype: 'client_credentials',
  clientid: '7tj4d2jf2kenqkra76ga751omni',
  clientsecret: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiomni',
  clientidunico: '7tj4d2jf2kenqkra76ga751clienteunico',
  clientsecretunico:
    'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiclienteunico',
  urlAmauta: 'https://api.dev.amauta.api-ngr.com',

  //DESARROLLO
  // urlSecurity: 'http://vsrvprdweb01:9999',
  // urlCupones: 'http://VSRVDEVAPP07.ngr.com.pe:9837',
  // urlInterfazProducto: 'http://VSRVDEVAPP07.ngr.com.pe:9838',
  // urlCuadratura: 'http://VSRVDEVAPP07.ngr.com.pe:9839',
  // urlEjecutor: 'http://VSRVDEVAPP07.ngr.com.pe:9845',
  // urlEjecutorSybase: 'http://VSRVDEVAPP07.ngr.com.pe:9753',
  // urlInterfaz: 'http://VSRVDEVAPP07.ngr.com.pe:9842',
  // urlReporte: 'http://VSRVDEVAPP07.ngr.com.pe:9811',
  // urlCierre: 'http://VSRVDEVAPP07.ngr.com.pe:9899',
  // urlRrhh: 'http://VSRVDEVAPP07.ngr.com.pe:9822',
  // urlOmnicanal: 'http://VSRVDEVAPP07.ngr.com.pe:9833',
  // urlSecurityShared: 'http://vsrvDEVweb01.ngr.com.pe/security-shared',
  // urlGenesys: 'https://genesys.dev.audex.api-ngr.com/genesys',
  //urlOmnicanalA: 'https://api.dev.omnicanal.api-ngr.com/motorpromocion',
  // urlTstdrpApi: 'https://prod.api-ngr.com/oauth2/token',
  //urlCarta: 'http://VSRVDEVAPP07.ngr.com.pe:9833/api/omnicanal',
  // gtype: 'client_credentials',
  // clientid: '7tj4d2jf2kenqkra76ga751omni',
  //clientsecret: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliigen',
  // clientidunico: '7tj4d2jf2kenqkra76ga751clienteunico',
  // clientsecretunico:
  //   'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiclienteunico',
  // urlAmauta: 'https://api.dev.amauta.api-ngr.com',

  //QA
  //urlOmnicanalA: 'https://api-qa.dev.omnicanal.api-ngr.com/motorpromocion',
  //urlCarta: 'http://VSRVDEVAPP07.ngr.com.pe:9833/api/omnicanal',
  //urlTstdrpApi: 'https://tstdrp.api-ngr.com/oauth2/token',
  //clientsecret: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliigen',
};
