export const environment = {
    production: false,
    //QA
    urlSecurity: 'http://vsrVQAAPP.ngr.com.pe:9999',
    urlCupones: 'http://vsrVQAAPP.ngr.com.pe:9837',
    urlInterfazProducto: 'http://vsrVQAAPP.ngr.com.pe:9838',
    urlCuadratura: 'http://vsrVQAAPP.ngr.com.pe:9839',
    urlEjecutor: 'http://vsrVQAAPP.ngr.com.pe:9845',
    urlEjecutorSybase: 'http://vsrVQAAPP.ngr.com.pe:9753',
    urlInterfaz: 'http://vsrVQAAPP.ngr.com.pe:9842',
    urlInterfazBB: 'http://vsrVQAAPP.ngr.com.pe:9841',
    urlInterfazDB: 'http://vsrVQAAPP.ngr.com.pe:9843',
    urlInterfazPP: 'http://vsrVQAAPP.ngr.com.pe:9844',
    urlInterfazCW: 'http://vsrVQAAPP.ngr.com.pe:9845',
    urlInterfazPJ: 'http://vsrVQAAPP.ngr.com.pe:9847',
    urlInterfazDD: 'http://vsrVQAAPP.ngr.com.pe:9848',
    urlReporte: 'http://vsrVQAAPP.ngr.com.pe:9811',
    urlCierre: 'http://vsrVQAAPP.ngr.com.pe:9899',
    urlRrhh: 'http://vsrVQAAPP.ngr.com.pe:9822',
    urlOmnicanal: 'http://vsrVQAAPP.ngr.com.pe:9833',
    urlSecurityShared: 'http://vsrvprdweb01.ngr.com.pe/security-shared',
    urlGenesys: 'https://genesys.dev.audex.api-ngr.com/genesys',
    urlOmnicanalA: 'https://api.omnicanal.api-ngr.com/motorpromocion',
    urlTstdrpApi: 'https://prod.api-ngr.com/oauth2/token',
    urlCarta: 'http://vsrVQAAPP.ngr.com.pe:9833/api/omnicanal',
    gtype: 'client_credentials',
    clientid: '7tj4d2jf2kenqkra76ga751omni',
    clientsecret: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiomni',
    clientsecretdescuento: 'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliigen',
    clientidunico: '7tj4d2jf2kenqkra76ga751clienteunico',
    clientsecretunico:
      'mgps0alo77vpdviokkumq2njk3vggki7rnam9ho02sluvliiclienteunico',
    urlAmauta: 'https://api.dev.amauta.api-ngr.com',
  };
  